services:
  # PostgreSQL with PostGIS
  postgres:
    image: postgis/postgis:15-3.3
    container_name: safar_sathi_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: safar_sathi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - safar_sathi_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d safar_sathi"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for caching and pub/sub
  redis:
    image: redis:7.2-alpine
    container_name: safar_sathi_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - safar_sathi_network
    command: redis-server --appendonly yes --requirepass redis123
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  

# Named volumes for data persistence
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

# Custom network
networks:
  safar_sathi_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
